# se só digitar "make" vai executar a primeira regra, que é "build" neste caso

build:
	gcc -Wall -std=c99 ./src/*.c -lSDL2 -o game 
# -lSDL2 é pra linkar a biblioteca no compilador

run:
	./game

clean:
	rm game